/*
 * Very simple APEX-defined class to store picklists
 *
 * Dynacat version used in the Dynacat Configurator Flow.
 *
 * DISCLAIMER: This is sample code only released under the CC0.
 * It is not of production quality, and is not warranted for quality or fitness 
 * for purpose by me or my employer.
*/

public class PicklistValue_Dynacat {
        @AuraEnabled public String label;
        @AuraEnabled public String value;
}